apiVersion: v1
kind: ConfigMap
metadata:
  name: sre-demo-api-config
  namespace: sre-demo
  labels:
    app.kubernetes.io/name: sre-demo-api
    purpose: sre-demo
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_HTTP_PORTS: "8080"
  DOTNET_EnableDiagnostics: "0"
  DOTNET_RUNNING_IN_CONTAINER: "true"
