apiVersion: v1
kind: Service
metadata:
  name: sre-demo-api
  namespace: sre-demo
  labels:
    app.kubernetes.io/name: sre-demo-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sre-demo-api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
