apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre-demo-api
  namespace: sre-demo
  labels:
    app.kubernetes.io/name: sre-demo-api
  annotations:
    azure.workload.identity/client-id: "__AZURE_CLIENT_ID__"
automountServiceAccountToken: false
